### PR TITLE
Book title change

### PR DESCRIPTION
**Pull request by nkoeries**
Sample is becoming an actual book so title had to reflect that.

### CODE REVIEW

**Comment by arthurattwell** [comment]
Thanks!

**Comment by emmaattwell** [comment]
Caring for mothers and babies: A guide for community health workers?

**Comment by arthurattwell** [comment]
@emmaattwell I think that would be better. For now @nkoeries and I (during Git training) went with exactly what Dave proposed. Can you include your suggestion in your editorial input while doing the markdown, perhaps in a cover letter?

**Comment by emmaattwell** [comment]
Cool. Will do.

**Pull request merged**
