### PR TITLE
FHRH and CHW-MBC

### PR DESCRIPTION
**Pull request by nkoeries**
At this stage I only need the FHRH and CHW-MBC files to be updated.

### CODE REVIEW

**Comment by arthurattwell** [comment]
@nkoeries If I merge this in, we'll get all the changes into master at once. Is it a problem if I merge in the changes to NC etc.? I.e. is anything there work-in-progress that should definitely not make it into master?

**Comment by nkoeries** [comment]
@arthurattwell, there is nothing here that shouldn't be updated so that shouldn't be an issue.

**Comment by arthurattwell** [comment]
@nkoeries Thanks! Merging.

**Comment by arthurattwell** [comment]
@nkoeries Your next step is to add the books to the index page to users can find them. I've written this up [here](https://github.com/BettercareHealth/bettercare/issues/98).

**Pull request merged**
